// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TideOfDestiniy.DAL.Context;

#nullable disable

namespace TideOfDestiniy.DAL.Migrations
{
    [DbContext(typeof(TideOfDestinyDbContext))]
<<<<<<<< HEAD:TideOfDestiniy/TideOfDestiniy.DAL/Migrations/20251027030205_InitialCreate.Designer.cs
    [Migration("20251027030205_InitialCreate")]
========
    [Migration("20251026103418_InitialCreate")]
>>>>>>>> GithubReleaseUpload:TideOfDestiniy/TideOfDestiniy.DAL/Migrations/20251026103418_InitialCreate.Designer.cs
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TideOfDestiniy.DAL.Entities.GameBuild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FileSizeMB")
                        .HasColumnType("integer");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("boolean");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("GameBuilds");
                });

            modelBuilder.Entity("TideOfDestiniy.DAL.Entities.GameFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
<<<<<<<< HEAD:TideOfDestiniy/TideOfDestiniy.DAL/Migrations/20251027030205_InitialCreate.Designer.cs
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");
========
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");
>>>>>>>> GithubReleaseUpload:TideOfDestiniy/TideOfDestiniy.DAL/Migrations/20251026103418_InitialCreate.Designer.cs

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAt")
<<<<<<<< HEAD:TideOfDestiniy/TideOfDestiniy.DAL/Migrations/20251027030205_InitialCreate.Designer.cs
                        .HasColumnType("timestamp with time zone");
========
                        .HasColumnType("datetime(6)");
>>>>>>>> GithubReleaseUpload:TideOfDestiniy/TideOfDestiniy.DAL/Migrations/20251026103418_InitialCreate.Designer.cs

                    b.HasKey("Id");

                    b.ToTable("GameFiles");
                });

<<<<<<<< HEAD:TideOfDestiniy/TideOfDestiniy.DAL/Migrations/20251027030205_InitialCreate.Designer.cs
            modelBuilder.Entity("TideOfDestiniy.DAL.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AltText")
                        .HasColumnType("text");

                    b.Property<Guid>("NewsId")
                        .HasColumnType("uuid");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NewsId");

                    b.ToTable("Images");
                });

========
>>>>>>>> GithubReleaseUpload:TideOfDestiniy/TideOfDestiniy.DAL/Migrations/20251026103418_InitialCreate.Designer.cs
            modelBuilder.Entity("TideOfDestiniy.DAL.Entities.News", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("NewsCategory")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
<<<<<<<< HEAD:TideOfDestiniy/TideOfDestiniy.DAL/Migrations/20251027030205_InitialCreate.Designer.cs
                            Id = new Guid("bd11cb8b-5268-474b-8220-7ec420db44d2"),
                            AuthorId = new Guid("c1d2e3f4-a5b6-4c7d-8e9f-0a1b2c3d4e5a"),
                            Content = "Nhiều tính năng mới và sửa lỗi...",
                            NewsCategory = 0,
                            PublishedAt = new DateTime(2025, 10, 27, 3, 2, 5, 501, DateTimeKind.Utc).AddTicks(2708),
========
                            Id = new Guid("d5b45c29-6a51-49f0-b03d-92ca793a516c"),
                            AuthorId = new Guid("c1d2e3f4-a5b6-4c7d-8e9f-0a1b2c3d4e5a"),
                            Content = "Nhiều tính năng mới và sửa lỗi...",
                            NewsCategory = 0,
                            PublishedAt = new DateTime(2025, 10, 26, 10, 34, 17, 166, DateTimeKind.Utc).AddTicks(2239),
>>>>>>>> GithubReleaseUpload:TideOfDestiniy/TideOfDestiniy.DAL/Migrations/20251026103418_InitialCreate.Designer.cs
                            Title = "Bản cập nhật lớn 2.5 đã ra mắt!",
                            Version = "2.5.0"
                        },
                        new
                        {
<<<<<<<< HEAD:TideOfDestiniy/TideOfDestiniy.DAL/Migrations/20251027030205_InitialCreate.Designer.cs
                            Id = new Guid("b7d471c4-ed2b-46db-aa4d-2fa46911d22b"),
                            AuthorId = new Guid("c1d2e3f4-a5b6-4c7d-8e9f-0a1b2c3d4e5a"),
                            Content = "Tham gia ngay để nhận phần thưởng hấp dẫn...",
                            NewsCategory = 1,
                            PublishedAt = new DateTime(2025, 10, 27, 3, 2, 5, 501, DateTimeKind.Utc).AddTicks(2720),
========
                            Id = new Guid("ec1c2d17-cd4b-4928-a70a-5d59683183ca"),
                            AuthorId = new Guid("c1d2e3f4-a5b6-4c7d-8e9f-0a1b2c3d4e5a"),
                            Content = "Tham gia ngay để nhận phần thưởng hấp dẫn...",
                            NewsCategory = 1,
                            PublishedAt = new DateTime(2025, 10, 26, 10, 34, 17, 166, DateTimeKind.Utc).AddTicks(2244),
>>>>>>>> GithubReleaseUpload:TideOfDestiniy/TideOfDestiniy.DAL/Migrations/20251026103418_InitialCreate.Designer.cs
                            Title = "Sự kiện Mùa Hè Rực Lửa bắt đầu!"
                        });
                });

            modelBuilder.Entity("TideOfDestiniy.DAL.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Player"
                        });
                });

            modelBuilder.Entity("TideOfDestiniy.DAL.Entities.SystemRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DirectXVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Graphics")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Memory")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OS")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Processor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Storage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SystemRequirements");
                });

            modelBuilder.Entity("TideOfDestiniy.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
<<<<<<<< HEAD:TideOfDestiniy/TideOfDestiniy.DAL/Migrations/20251027030205_InitialCreate.Designer.cs
                        .HasColumnType("text");
========
                        .HasColumnType("longtext");
>>>>>>>> GithubReleaseUpload:TideOfDestiniy/TideOfDestiniy.DAL/Migrations/20251026103418_InitialCreate.Designer.cs

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1d2e3f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f"),
<<<<<<<< HEAD:TideOfDestiniy/TideOfDestiniy.DAL/Migrations/20251027030205_InitialCreate.Designer.cs
                            CreatedAt = new DateTime(2025, 10, 27, 3, 2, 5, 501, DateTimeKind.Utc).AddTicks(2636),
========
                            CreatedAt = new DateTime(2025, 10, 26, 10, 34, 17, 166, DateTimeKind.Utc).AddTicks(2091),
>>>>>>>> GithubReleaseUpload:TideOfDestiniy/TideOfDestiniy.DAL/Migrations/20251026103418_InitialCreate.Designer.cs
                            Email = "admin@tideofdestiny.com",
                            EmailConfirmed = true,
                            PasswordHash = "$2a$11$Qm/C/LMke5VZ91Ezxk73I.5dsbIqlWHrzzkG8h9f2yUZjPwIwD6ZW",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("c1d2e3f4-a5b6-4c7d-8e9f-0a1b2c3d4e5a"),
<<<<<<<< HEAD:TideOfDestiniy/TideOfDestiniy.DAL/Migrations/20251027030205_InitialCreate.Designer.cs
                            CreatedAt = new DateTime(2025, 10, 27, 3, 2, 5, 501, DateTimeKind.Utc).AddTicks(2649),
========
                            CreatedAt = new DateTime(2025, 10, 26, 10, 34, 17, 166, DateTimeKind.Utc).AddTicks(2116),
>>>>>>>> GithubReleaseUpload:TideOfDestiniy/TideOfDestiniy.DAL/Migrations/20251026103418_InitialCreate.Designer.cs
                            Email = "player@gmail.com",
                            EmailConfirmed = true,
                            PasswordHash = "$2a$11$Qm/C/LMke5VZ91Ezxk73I.5dsbIqlWHrzzkG8h9f2yUZjPwIwD6ZW",
                            Username = "player1"
                        });
                });

            modelBuilder.Entity("TideOfDestiniy.DAL.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("c1d2e3f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f"),
                            RoleId = 1
                        },
                        new
                        {
                            UserId = new Guid("c1d2e3f4-a5b6-4c7d-8e9f-0a1b2c3d4e5a"),
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("TideOfDestiniy.DAL.Entities.Image", b =>
                {
                    b.HasOne("TideOfDestiniy.DAL.Entities.News", "News")
                        .WithMany("Images")
                        .HasForeignKey("NewsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("News");
                });

            modelBuilder.Entity("TideOfDestiniy.DAL.Entities.News", b =>
                {
                    b.HasOne("TideOfDestiniy.DAL.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("TideOfDestiniy.DAL.Entities.UserRole", b =>
                {
                    b.HasOne("TideOfDestiniy.DAL.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TideOfDestiniy.DAL.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TideOfDestiniy.DAL.Entities.News", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("TideOfDestiniy.DAL.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("TideOfDestiniy.DAL.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
